package io.github.kuugasky.kuugatool.sql;

import org.junit.jupiter.api.Test;

public class MysqlStatementsUtilTest {

    String sql = "" +
            "create definer = pywkf@`%` view v_housesouce_chkokexp_week as\n" +
            "select `thi`.`FCITY_CODE`                                                                                                                                                                                                                                                                                                                                                                                       AS `城市`,\n" +
            "       `thi`.`FEXTEND_PERSON_ORG_NAME`                                                                                                                                                                                                                                                                                                                                                                          AS `拓房人门店`,\n" +
            "       `thi`.`FEXTEND_PERSON_NAME`                                                                                                                                                                                                                                                                                                                                                                              AS `拓房人名称`,\n" +
            "       `extendperson`.`FCODE`                                                                                                                                                                                                                                                                                                                                                                                   AS `拓房人工号`,\n" +
            "       `thi`.`FROOM_NUMBER`                                                                                                                                                                                                                                                                                                                                                                                     AS `房源编码`,\n" +
            "       `tddg`.`FNAME`                                                                                                                                                                                                                                                                                                                                                                                           AS `楼盘名称`,\n" +
            "       `thi`.`FHOUSE_EXTEND_TIME`                                                                                                                                                                                                                                                                                                                                                                               AS `拓房时间`,\n" +
            "       `thi`.`FCREATE_TIME`                                                                                                                                                                                                                                                                                                                                                                                     AS `验真单生成时间`,\n" +
            "       `thi`.`FCOMPLETION_TIME`                                                                                                                                                                                                                                                                                                                                                                                 AS `验真单结束时间`,\n" +
            "       (case `thi`.`FHOUSE_TYPE` when 'RENT' then '租' when 'SELL' then '售' when 'RENT_SELL' then '租售' else '' end)                                                                                                                                                                                                                                                                                              AS `房源状态`,\n" +
            "       (case `thi`.`FINSPECTION_TYPE` when 'ADD_INSPECTION' then '新增验真' when 'STOCK_INSPECTION' then '库存验真' when 'ADD_HOUSE_PRE' then '预录入新增验真' end)                                                                                                                                                                                                                                                            AS `验真类型`,\n" +
            "       (case `thi`.`FINSPECTION_APPLY_STATUS` when 'RENT_INSPECTION' then '租验真' when 'SELL_INSPECTION' then '售验真' else '' end)                                                                                                                                                                                                                                                                                  AS `申请状态`,\n" +
            "       (case `thi`.`FINSPECTION_STATUS` when 'WAIT_INSPECTION' then '待验真' when 'PROOF_WAIT_INSPECTION' then '举证待核查' when 'PASSED_INSPECTION' then '验真通过' when 'NOT_PASSED_INSPECTION' then '验真未通过' when 'TIMEOUT_NOT_INSPECTION' then '超时未验真' when 'HAD_VERIFY_INVALID' then '房源已核销' else '' end)                                                                                                               AS `验真状态`,\n" +
            "       (case `thip`.`FNOT_PASS_REASON` when 'PHONE_INVALID' then '电话号码无效' when 'NOT_RENT_OR_NOT_SELL' then '不租/不售' when 'HAD_RENT_OR_HAD_SELL' then '已租/已售' when 'LACK_OF_EVIDENCE' then '证据不足' else '' end)                                                                                                                                                                                                    AS `不通过原因`,\n" +
            "       `thi`.`FSEND_SMS_COUNT`                                                                                                                                                                                                                                                                                                                                                                                  AS `短信发送数`,\n" +
            "       `thi`.`FINPUT_CODE_COUNT`                                                                                                                                                                                                                                                                                                                                                                                AS `委托码输入次数`,\n" +
            "       `thip`.`FCREATE_TIME`                                                                                                                                                                                                                                                                                                                                                                                    AS `举证时间`,\n" +
            "       if((isnull(`thip`.`FPROOF_TYPE`) or (`thip`.`FPROOF_TYPE` = '')), (select group_concat((case `ie`.`FEVIDENCE_TYPE` when 'IMAGE' then '图片' when 'VIDEO' then '视频' when 'AUDIO_FOLLOW' then '录音跟进' when 'LOCAL_AUDIO' then '本地录音' when 'NULL_PROOF' then '证据为空' else '' end) separator ',') from `kuuga_house`.`t_house_inspection_evidence` `ie` where (`ie`.`FINSPECTION_PROOF_ID` = `thip`.`FID`)), '') AS `举证类型`,\n" +
            "       `thip`.`FAUDITOR_NAME`                                                                                                                                                                                                                                                                                                                                                                                   AS `审核人员名称`,\n" +
            "       `thip`.`FAUDIT_REMARK`                                                                                                                                                                                                                                                                                                                                                                                   AS `审核备注`,\n" +
            "       if((`thi`.`FCOMPLETION_TIME` is not null), concat(timestampdiff(HOUR, `thi`.`FCREATE_TIME`, `thi`.`FCOMPLETION_TIME`), '.', (timestampdiff(MINUTE, `thi`.`FCREATE_TIME`, `thi`.`FCOMPLETION_TIME`) % 60)), '')                                                                                                                                                                                           AS `验真时效`,\n" +
            "       (case `thi`.`FINSPECTION_WAY` when 'OWNER_SMS_INSPECTION' then '业主短信验真' when 'EXTEND_PERSON_PROOF' then '拓房人举证' when 'SURVEY_INSPECTION' then '实勘验真' when 'KEY_INSPECTION' then '钥匙验真' when 'ENTRUST_INSPECTION' then '委托验真' when 'ADD_INTENTION' then '新增意向' when 'HOUSE_TRADE' then '房源成交' else '' end)                                                                                                AS `验真方式`,\n" +
            "       if((`thi`.`FINSPECTION_WAY` = 'OWNER_SMS_INSPECTION'), `sms`.`FOWNER_PHONE`, NULL)                                                                                                                                                                                                                                                                                                                       AS `验真号码`,\n" +
            "       if((`thi`.`FINSPECTION_WAY` = 'OWNER_SMS_INSPECTION'), `sms`.`houseCount`, 0)                                                                                                                                                                                                                                                                                                                            AS `验真号码房源量`,\n" +
            "       if((`thi`.`FINSPECTION_WAY` = 'OWNER_SMS_INSPECTION'), if((`tho`.`FMAIN_PHONE` = 'YES'), '是', '否'), '')                                                                                                                                                                                                                                                                                                  AS `验真号码当前是否为主要联系方式`,\n" +
            "       if((`thi`.`FINSPECTION_WAY` = 'OWNER_SMS_INSPECTION'), if((`tho`.`FENABLED_STATUS` = 'DISABLED'), '是', '否'), '')                                                                                                                                                                                                                                                                                         AS `验真号码当前是否已删除`,\n" +
            "       (select if((`kuuga_house`.`t_house_key_person`.`FENABLED_STATUS` = 'ENABLED'), '否', '是') from `kuuga_house`.`t_house_key_person` where ((`kuuga_house`.`t_house_key_person`.`FROOM_ID` = `thi`.`FROOM_ID`) and (`thi`.`FINSPECTION_WAY` = 'KEY_INSPECTION')) order by `kuuga_house`.`t_house_key_person`.`FUPDATE_TIME` desc limit 1)                                                                    AS `房源钥匙是否已取消`,\n" +
            "       (select `kuuga_house`.`t_house_key_person`.`FCANCEL_TIME` from `kuuga_house`.`t_house_key_person` where ((`kuuga_house`.`t_house_key_person`.`FROOM_ID` = `thi`.`FROOM_ID`) and (`thi`.`FINSPECTION_WAY` = 'KEY_INSPECTION')) order by `kuuga_house`.`t_house_key_person`.`FUPDATE_TIME` desc limit 1)                                                                                                   AS `钥匙取消时间`\n" +
            "from (((((`kuuga_house`.`t_house_inspection` `thi` left join `kuuga_house`.`t_house_inspection_proof` `thip` on ((`thi`.`FID` = `thip`.`FINSPECTION_ID`))) left join `kuuga_dts`.`t_dts_dict_garden` `tddg` on ((`thi`.`FGARDEN_ID` = `tddg`.`FID`))) left join (select max(`sj`.`FCREATE_TIME`) AS `max(sj.FCREATE_TIME)`, count(distinct `s`.`FHOUSE_ID`) AS `houseCount`, `s`.`FOWNER_PHONE` AS `FOWNER_PHONE`, `sj`.`FHOUSE_INSPECTION_ID` AS `thiFID`\n" +
            "                                                                                                                                                                                                                                                                 from (`kuuga_house`.`t_house_inspection_sms_detail` `s`\n" +
            "                                                                                                                                                                                                                                                                          left join `kuuga_house`.`t_house_inspection_sms_join` `sj` on ((`sj`.`FHOUSE_INSPECTION_SMS_ID` = `s`.`FID`)))\n" +
            "                                                                                                                                                                                                                                                                 group by `s`.`FID`) `sms` on ((`thi`.`FID` = `sms`.`thiFID`))) left join `dts_infra_oa`.`t_person` `extendperson` on ((`extendperson`.`FID` = `thi`.`FEXTEND_PERSON_ID`)))\n" +
            "         left join (select `ho`.`FENABLED_STATUS` AS `FENABLED_STATUS`, `ho`.`FHOUSE_ID` AS `FHOUSE_ID`, `ho`.`FPHONE` AS `FPHONE`, `ho`.`FMAIN_PHONE` AS `FMAIN_PHONE` from `kuuga_house`.`t_house_owner` `ho`) `tho` on (((`tho`.`FPHONE` = `sms`.`FOWNER_PHONE`) and (`tho`.`FHOUSE_ID` = `thi`.`FHOUSE_ID`))))\n" +
            "where ((1 = 1) and (date_format(`thi`.`FCREATE_TIME`, '%Y-%m-%d %H:%i:%s') between (select date_format((curdate() + interval -(1) week), '%Y-%m-%d %H:%i:%s')) and (select (curdate() - interval 1 second))) and (`thi`.`FENABLED_STATUS` = 'ENABLED'));\n" +
            "";

    @Test
    public void isValid() {
        System.out.println(MysqlStatementsUtil.isValid(sql));
    }

    @Test
    public void sqlFormat() {
        System.out.println(MysqlStatementsUtil.sqlFormat(sql));
    }

    @Test
    public void sqlFormatUpperCase() {
        System.out.println(MysqlStatementsUtil.sqlFormatUpperCase(sql));
    }

    @Test
    public void sqlUpperCase() {
        System.out.println(MysqlStatementsUtil.sqlUpperCase(sql));
    }

    @Test
    public void sqlSimplify() {
        System.out.println(MysqlStatementsUtil.sqlSimplify(sql));
    }

    @Test
    public void sqlSimplifyAndRemoveBackquote() {
        System.out.println(MysqlStatementsUtil.sqlSimplify(sql, true));
    }

}